// This file is generated by `pnpm wedding:images`.
// Change the source photos or processing script instead of editing this file directly.
export const weddingGallery = [
  {
    "id": "wedding-gallery-01",
    "src": "/images/wedding/gallery/full/gallery-01.webp",
    "alt": "웨딩 갤러리 사진 1",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-02",
    "src": "/images/wedding/gallery/full/gallery-02.webp",
    "alt": "웨딩 갤러리 사진 2",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-03",
    "src": "/images/wedding/gallery/full/gallery-03.webp",
    "alt": "웨딩 갤러리 사진 3",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-04",
    "src": "/images/wedding/gallery/full/gallery-04.webp",
    "alt": "웨딩 갤러리 사진 4",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-05",
    "src": "/images/wedding/gallery/full/gallery-05.webp",
    "alt": "웨딩 갤러리 사진 5",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-06",
    "src": "/images/wedding/gallery/full/gallery-06.webp",
    "alt": "웨딩 갤러리 사진 6",
    "width": 1200,
    "height": 900
  },
  {
    "id": "wedding-gallery-07",
    "src": "/images/wedding/gallery/full/gallery-07.webp",
    "alt": "웨딩 갤러리 사진 7",
    "width": 1200,
    "height": 900
  },
  {
    "id": "wedding-gallery-08",
    "src": "/images/wedding/gallery/full/gallery-08.webp",
    "alt": "웨딩 갤러리 사진 8",
    "width": 1200,
    "height": 900
  },
  {
    "id": "wedding-gallery-09",
    "src": "/images/wedding/gallery/full/gallery-09.webp",
    "alt": "웨딩 갤러리 사진 9",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-10",
    "src": "/images/wedding/gallery/full/gallery-10.webp",
    "alt": "웨딩 갤러리 사진 10",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-11",
    "src": "/images/wedding/gallery/full/gallery-11.webp",
    "alt": "웨딩 갤러리 사진 11",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-12",
    "src": "/images/wedding/gallery/full/gallery-12.webp",
    "alt": "웨딩 갤러리 사진 12",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-13",
    "src": "/images/wedding/gallery/full/gallery-13.webp",
    "alt": "웨딩 갤러리 사진 13",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-14",
    "src": "/images/wedding/gallery/full/gallery-14.webp",
    "alt": "웨딩 갤러리 사진 14",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-15",
    "src": "/images/wedding/gallery/full/gallery-15.webp",
    "alt": "웨딩 갤러리 사진 15",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-16",
    "src": "/images/wedding/gallery/full/gallery-16.webp",
    "alt": "웨딩 갤러리 사진 16",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-17",
    "src": "/images/wedding/gallery/full/gallery-17.webp",
    "alt": "웨딩 갤러리 사진 17",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-18",
    "src": "/images/wedding/gallery/full/gallery-18.webp",
    "alt": "웨딩 갤러리 사진 18",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-19",
    "src": "/images/wedding/gallery/full/gallery-19.webp",
    "alt": "웨딩 갤러리 사진 19",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-20",
    "src": "/images/wedding/gallery/full/gallery-20.webp",
    "alt": "웨딩 갤러리 사진 20",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-21",
    "src": "/images/wedding/gallery/full/gallery-21.webp",
    "alt": "웨딩 갤러리 사진 21",
    "width": 1200,
    "height": 800
  },
  {
    "id": "wedding-gallery-22",
    "src": "/images/wedding/gallery/full/gallery-22.webp",
    "alt": "웨딩 갤러리 사진 22",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-23",
    "src": "/images/wedding/gallery/full/gallery-23.webp",
    "alt": "웨딩 갤러리 사진 23",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-24",
    "src": "/images/wedding/gallery/full/gallery-24.webp",
    "alt": "웨딩 갤러리 사진 24",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-25",
    "src": "/images/wedding/gallery/full/gallery-25.webp",
    "alt": "웨딩 갤러리 사진 25",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-26",
    "src": "/images/wedding/gallery/full/gallery-26.webp",
    "alt": "웨딩 갤러리 사진 26",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-27",
    "src": "/images/wedding/gallery/full/gallery-27.webp",
    "alt": "웨딩 갤러리 사진 27",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-28",
    "src": "/images/wedding/gallery/full/gallery-28.webp",
    "alt": "웨딩 갤러리 사진 28",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-29",
    "src": "/images/wedding/gallery/full/gallery-29.webp",
    "alt": "웨딩 갤러리 사진 29",
    "width": 877,
    "height": 1200
  },
  {
    "id": "wedding-gallery-30",
    "src": "/images/wedding/gallery/full/gallery-30.webp",
    "alt": "웨딩 갤러리 사진 30",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-31",
    "src": "/images/wedding/gallery/full/gallery-31.webp",
    "alt": "웨딩 갤러리 사진 31",
    "width": 870,
    "height": 653
  },
  {
    "id": "wedding-gallery-32",
    "src": "/images/wedding/gallery/full/gallery-32.webp",
    "alt": "웨딩 갤러리 사진 32",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-33",
    "src": "/images/wedding/gallery/full/gallery-33.webp",
    "alt": "웨딩 갤러리 사진 33",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-34",
    "src": "/images/wedding/gallery/full/gallery-34.webp",
    "alt": "웨딩 갤러리 사진 34",
    "width": 900,
    "height": 1200
  },
  {
    "id": "wedding-gallery-35",
    "src": "/images/wedding/gallery/full/gallery-35.webp",
    "alt": "웨딩 갤러리 사진 35",
    "width": 900,
    "height": 1200
  }
] as const;
